name: Process Media files

on:
  push:
    paths:
      - '**'
      - '**/*.md'
      - '!.git/**'
      - '!.github/**'
      - '!.gitattributes'
      - '!.gitignore'
      - '!scripts/**'
      - '!files.yaml'

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install supabase

      - name: Get all changed media files
        id: changed-media-files
        uses: tj-actions/changed-files@v45
        with:
          recover_deleted_files: true
          recover_deleted_files_to_destination: 'actions/recovered'
          separator: ","
          files: |
            **
            **/*.md
            !.git/**
            !.github/**
            !.gitattributes
            !.gitignore
            !scripts/**
            !files.yaml

      - name: List all changed media files
        if: steps.changed-media-files.outputs.any_changed == 'true'
        run: |
           IFS=$',' read -a MODIFIED_FILES_ARRAY <<< "${{ steps.changed-media-files.outputs.all_modified_files }}"
           for file in "${MODIFIED_FILES_ARRAY[@]}"; do
             echo $file
           done
        shell:
           bash 

      - name: Process changes
        env:
          CHANGED_MEDIA_FILES: ${{ steps.changed-media-files.outputs.modified_files }}
          ADDED_MEDIA_FILES: ${{ steps.changed-media-files.outputs.added_files }}
          DELETED_MEDIA_FILES: ${{ steps.changed-media-files.outputs.deleted_files }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          GITHUB_REPOSITORY_URL: ${{ github.repository }}
        run: python scripts/update_buckets.py
